version: "3.9"
   
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5001"
    volumes:
      - .:/code
    ports:
      - "5001:5001"